env:
    credentials: "ENCRYPTED[!1929de459463acec92461f8ad6b8b3ea0f6a3bfd7e1476c04da2a22a8ec24c8857bcf7d91ec0bde5b31c886132a2159f!]"
    rcloneconfig: "ENCRYPTED[!7da59da68dd57c591efdcd09524e695fbb128da55374a5abd229007db7acbea60ffc4bdfa930c2a7f6ea8fc60d821247!]"
    tokentl: "ENCRYPTED[!8a7f36bd46b860ebd3efdcb606be7de3d9339bb8b5ed5cddd312e3f25ba789e3f1b51d88913cf0b5724f5f48c5a8c52c!]"
    idtl: "ENCRYPTED[!1c0e8fb249a2570a58b7193232234f7f42154dc0e3f45be2baf8ed5ff139039b68d4db9b17b72e15047253ee990dbf55!]"
    lunch: lunch aosp_ysl-userdebug
    make: make bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "R.A.P"
       - git config --global user.email "rhmd.19801@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy venyx:arcana/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh
  
  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p ~/rom
      - cd ~/rom
      - rm -rf * .repo
      - mkdir -p ~/.anu
      - export PATH="~/.anu:$PATH"
      - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/.anu/repoo
      - chmod a+x ~/.anu/repoo
      - repoo init -q --no-repo-verify --depth=1 -u https://github.com/arcana-ext/manifest -b 12.x -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/OhMyVenyx/local_manifest -b arcana-12.1 --depth 1 .repo/local_manifests
      - repoo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="venyx"
      - export BUILD_HOSTNAME="IDN-Labs"
      - export BUILD_WITH_COLORS=1
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build Started!"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls Arcana*.zip) Completed!"

  Upload_script:
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd ~/rom/out/target/product/ysl/ && ls Arcana*.zip)"
#      - rclone copy ~/rom/out/target/product/ysl/Arcana*.zip venyx:ysl -P
#      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/ysl/ && ls Arcana*.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz venyx:arcana -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Ccache Uploaded Successfully!"
