env:
    credentials: "ENCRYPTED[!efab3ed4529d2ffe013709890c8be3abf5839a337f965dc607d8c43bb57a39e7d52ff756687bc92c198f87199c03abc1!]"
    rcloneconfig: "ENCRYPTED[!de9a884ad227a93ee08eb71e4492fb073234531abe6999b0e234f22be251fa381b2c090dc28399c8904a38aa4fde9412!]"
    tokentl: "ENCRYPTED[!794f286e43a45e476ba1bd2c0ad76de5872b085136e36b0d645d7531bb3b90737f3447bf5571cf4420e5b9743ce88061!]"
    idtl: "ENCRYPTED[!d0a22747709d8cc7482c5f0e1c926b7e3dddfc3e126a08649f543c0a47fba70b243a1b766cd01f4f1765978b8cf53642!]"
    lunch : lunch bootleg_juice-userdebug
    make: make bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build"
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "darknius20"
       - git config --global user.email "darknius20@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p /tmp/ccache
       - rclone copy darknius20:bootleg/ccache.tar.gz /tmp -P
       - cd /tmp
       - time tar xf ccache.tar.gz
       - cd /tmp
  
  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./s.sh
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Start sync Source"
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - rm -rf * .repo
      - rm -rf ~/rom/* .repo
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/BootleggersROM/manifest.git -b queso -g default,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      # DT/VT/KT/TC
      - git clone --depth=1 https://github.com/Night-Raids-Reborn/device_xiaomi_juice_Q -b bootleg device/xiaomi/juice
      - git clone --depth=1 https://github.com/Night-Raids-Reborn/vendor-xiaomi-juice_Q --single-branch -b 10.staging vendor/xiaomi/juice
      - git clone --depth=1 https://github.com/Night-Raids-Reborn/DarkLegacy_kernel_citrus --single-branch -b protest kernel/xiaomi/juice
      - git clone --depth=1 https://github.com/Night-Raids-Reborn/proton-clang --single-branch -b master prebuilts/clang/host/linux-x86/clang-proton
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

      - echo "============================"
      - echo "Sync Completed!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/juice/ && ls Nusantara*.zip) Completed!"
      - echo "============================"
      - echo "Build Completed!"
      - echo "============================"

  Upload_script:
      - echo "============================"
      - echo "Uploading the Build...."
      - echo "============================"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/juice/ && ls *.zip)"
      - rclone copy /tmp/rom/out/target/product/juice/*.zip darknius20:juice -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd ~/rom/out/target/product/juice/ && ls *.zip) Uploaded Successfully!"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Compres ccache"
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading ccache...."
      - rclone copy ccache.tar.gz darknius20:bootleg -P
      - echo " "
      - echo "============================"
      - echo "Build Uploaded Successfully!"
      - echo "============================"
